---
name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  create:
  workflow_dispatch:

jobs:
  container:
    container: prikhi/avr-toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Firmware
        run: make
